baseURL = "https://mon-blog.vence.tech/"
languageCode = "en-en"
title = "Mon site Hugo"
theme = "ananke"

[params]
  github = "https://github.com/vences/hugo-workers"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/london.jpg"
