baseURL = "https://mon-blog.vence.tech/"
languageCode = "en-en"
title = "Mon site Hugo"
theme = "ananke"

[params]
  favicon = ""
  description = "Site de démo"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/vences/hugo-workers"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/london.jpg"
  recent_posts_number = 2
