name = "mon-blog"
type = "webpack"
account_id = ""
workers_dev = false
route = "mon-blog.vence.tech/*"
zone_id = "e1dff329fb167a506d1b814ceea7435d"

[site]
bucket = "./public"
entry-point = "workers-site"
